server:
  port: 8080 # Порт сервера
  error:
    include-message: always # Выводить сообщение в отловленной ошибке

spring:
  datasource:
    url: jdbc:h2:mem:homework
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop